// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YNCW947_MSqbKFQhS2yYm6J1lw4rnnE',
    appId: '1:907937113979:web:c46231bbc2652bcb1cffde',
    messagingSenderId: '907937113979',
    projectId: 'map-3eebf',
    authDomain: 'map-3eebf.firebaseapp.com',
    storageBucket: 'map-3eebf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHrNpcF68L2Qoys83igQphSlTNpftdUE',
    appId: '1:907937113979:android:ae7788e752127e941cffde',
    messagingSenderId: '907937113979',
    projectId: 'map-3eebf',
    storageBucket: 'map-3eebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-e4O5llikHte_1B9dpJKpqpiTlpY7YaE',
    appId: '1:907937113979:ios:ff7eff6e2ba320c31cffde',
    messagingSenderId: '907937113979',
    projectId: 'map-3eebf',
    storageBucket: 'map-3eebf.appspot.com',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-e4O5llikHte_1B9dpJKpqpiTlpY7YaE',
    appId: '1:907937113979:ios:ff7eff6e2ba320c31cffde',
    messagingSenderId: '907937113979',
    projectId: 'map-3eebf',
    storageBucket: 'map-3eebf.appspot.com',
    iosBundleId: 'com.example.map',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8YNCW947_MSqbKFQhS2yYm6J1lw4rnnE',
    appId: '1:907937113979:web:f48c8378254f6fcf1cffde',
    messagingSenderId: '907937113979',
    projectId: 'map-3eebf',
    authDomain: 'map-3eebf.firebaseapp.com',
    storageBucket: 'map-3eebf.appspot.com',
  );
}
